version: '3.8'

services:
  dr-dobby-agent:
    build: .
    container_name: dr-dobby-xmtp-agent
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - XMTP_NETWORK=${XMTP_NETWORK:-dev}
      - BOT_WALLET_PRIVATE_KEY=${BOT_WALLET_PRIVATE_KEY}
      - SENTIENT_DOBBY_API_URL=${SENTIENT_DOBBY_API_URL}
      - SENTIENT_DOBBY_API_KEY=${SENTIENT_DOBBY_API_KEY}
      - SENTIENT_DOBBY_MODEL=${SENTIENT_DOBBY_MODEL:-unhinged}
      - FALLBACK_API_URL=${FALLBACK_API_URL}
      - FALLBACK_API_KEY=${FALLBACK_API_KEY}
      - FALLBACK_MODEL=${FALLBACK_MODEL:-gpt-3.5-turbo}
      - MAX_REPLIES_PER_HOUR=${MAX_REPLIES_PER_HOUR:-50}
      - MAX_CONTEXT_LENGTH=${MAX_CONTEXT_LENGTH:-4000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    networks:
      - dr-dobby-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dr-dobby-network:
    driver: bridge
